### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by snowbldr** [newrelic/java-log-extensions#62]
I'm using the logback extension for newrelic and java agent version 6.4.2.

When I try to start up my spring boot application it fails to start with the following stack trace:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'java.util.Map com.newrelic.api.agent.Agent.getLinkingMetadata()'
    at com.newrelic.logging.logback.NewRelicAsyncAppender.preprocess(NewRelicAsyncAppender.java:39)
    at com.newrelic.logging.logback.NewRelicAsyncAppender.preprocess(NewRelicAsyncAppender.java:36)
    at ch.qos.logback.core.AsyncAppenderBase.append(AsyncAppenderBase.java:160)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
    at ch.qos.logback.classic.Logger.log(Logger.java:765)
    at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.error(LogAdapter.java:433)
    at org.springframework.boot.SpringApplication.reportFailure(SpringApplication.java:835)
    at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:799)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
```

https://github.com/newrelic/java-log-extensions/blob/main/logback/src/main/java/com/newrelic/logging/logback/NewRelicAsyncAppender.java#L39

I've had to disable newrelic logging for now.

**Comment by kford-newrelic** [comment]
@snowbldr thanks for letting us know about this issue

Does the issue occur in multiple environments (eg: dev, qa & prod)?

Are you able to try this with the latest version of our agent (maybe in a non-prod env) and let us know what happens?

**Comment by jasonjkeller** [comment]
Closing given the age of the ticket. It's unclear if this is still an issue, please feel free to reopen if need be.
